routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('events','EventsController')->middleware('auth');
Route::get('events/delete/{id}', 'EventsController@destroy')->name('events.delete');
Route::get('events/changestatus/{cid}/{sid}', 'EventsController@changeStatus')->name('events.changestatus')->middleware('auth');
Route::get('events.view/{id}', 'EventsController@details')->name('events.view');
Route::get('bid.create/{id}', 'EventsController@createbid')->name('bid.create');
Route::get('events.index/{id}', 'EventsController@createbid')->name('bid.create');
Route::get('myevents', 'EventsController@myEvents')->name('myevents');
Route::get('mybids', 'EventsController@myBids')->name('mybids');
Route::get('bidapprove/{id}', 'EventsController@bidapproved')->name('bidapprove');

Route::get('bid.details/{id}', 'EventsController@biddetails')->name('bids.details');

Route::get('users/delete/{id}', 'UsersController@destroy')->name('users.delete');
Route::get('users.index', 'UsersController@index')->name('users.index');
Route::get('users.edit/{id}', 'UsersController@edit')->name('users.edit');
Route::post('users.update/{id}', 'UsersController@update')->name('users.update');
Route::get('users.create', 'UsersController@create')->name('users.create');
Route::post('users.store', 'UsersController@store')->name('users.store');
Route::get('users.customers', 'UsersController@customers')->name('users.customers');
Route::get('users.photographer', 'UsersController@photographer')->name('users.photographer');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = ['date', 'contact_name_1', 'contact_email', 'contact_phone_number_1', 'contact_name_2', 'contact_phone_number_2', 'type', 'location', 'number_of_guests', 'notes', 'bid', 'bid_summary', 'status_id'];

    public function extras(){
        return $this->belongsToMany('App\Extra','event_extras');        
    }  

    public function users(){
        return $this->belongsToMany('App\User','event_users');        
    }  

    public function status(){
        return $this->belongsTo('App\Status', 'status_id');        
    }  

}    

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;
use App\Extra;
use App\EventExtra;
use App\Status;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class EventsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eve = Event::all();
        $statuses = Status::all();
        $events = $eve->sortByDesc('created_at');
        return view ('events.index', compact('events','statuses'));
    }

    public function bidindex()
    {
        $user = Auth::id();
        $event = Event::findOrFail($id);
        return view ('bids.index', compact('event'));
    }

    public function biddetails($id)
    {
        $event = Event::findOrFail($id);
        return view ('bids.details', compact('event'));
    }

    public function bidapproved($id)
    {
        $event = Event::findOrFail($id);
        $event->status_id = 3;
        $event->save();
        return view ('bids.index', compact('event'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $extras = Extra::all();

        return view ('events.create', compact('extras'));
    }

    public function myEvents(){
        $user_id = Auth::id();
        $eve = DB::table('events')->where('user_id',$user_id)->pluck('id');
        $events = Event::findOrFail($eve)->all();
        return view('events.index', compact('events'));
    }

    
    public function myBids(){
        $user_id = Auth::id();
        $eve = DB::table('events')->where('user_id',$user_id)->pluck('id');
        $events = Event::findOrFail($eve)->all();
        return view('bids.index', compact('events'));
    }
    public function changestatus($eid,$sid){
        $event = Event::findOrFail($eid);     
        $candidate->status_id = $sid;
        $candidate->save();

            Session::flash('success', 'The status was change successfully');
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function details($id){
        $event = Event::findOrFail($id);
        $eventextras = DB::table('event_extras')->where('event_id',$event->id)->pluck('extra_id');
        $extras = Extra::findOrFail($eventextras)->all();
        $statuses = Status::all();
        return view ('events.view', compact('event','extras','statuses'));
    }

    public function createbid($id){
        $event = Event::findOrFail($id);
        $statuses = Status::all();
        return view ('bids.create', compact('event', 'statuses'));
    }

    public function store(Request $request)
    {
        $event = new Event();
        $eve = $event->create($request->all());
        $eve->user_id = Auth::id();
        $eve->status_id = 1;
        $eve->save();
        $extras = Extra::all();
            if($request->checkbox1 == TRUE){
                EventExtra::create([
                    'event_id' => $eve->id,
                    'extra_id' => 1,
                    ]);
            }
            if($request->checkbox2 == TRUE){
                EventExtra::create([
                    'event_id' => $eve->id,
                    'extra_id' => 2,
                    ]);
            }
            if($request->checkbox3 == TRUE){
                EventExtra::create([
                    'event_id' => $eve->id,
                    'extra_id' => 3,
                    ]);
            }

        return redirect('events');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::findOrFail($id);
        $statuses = Status::all();
        return view ('events.edit', compact('event','statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $event = Event::findOrFail($id);
        $event->update($request->all());
        $event->bid = $request->bid;
        $event->bid_summary = $request->bid_summary;
        $event->status_id = $request->status_id;
        return redirect('events');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = Event::findOrFail($id);
        $event->delete();
        return redirect('events');
    }
}

resources/views/events/create.blade.php
@extends('layouts.app')

@section('content')
                   
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Submit request') }}</div>
        
                        <div class="card-body">
                            <form method="POST" action="{{ route('events.store') }}">
                                @csrf
        
                                <div class="form-group row">
                                    <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Event Date') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="date" type="date" class="form-control @error('date') is-invalid @enderror" name="date" value="{{ old('date') }}" required autocomplete="date" autofocus>
        
                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
        
                                <div class="form-group row">
                                    <label for="contact_name_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Name') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="contact_name_1" type="text" class="form-control @error('email') is-invalid @enderror" name="contact_name_1" value="{{ old('contact_name_1') }}" required autocomplete="contact_name_1">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="contact_email" type="email" class="form-control @error('email') is-invalid @enderror" name="contact_email" value="{{ old('contact_email') }}" required autocomplete="contact_email">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_phone_number_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Phone') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="contact_phone_number_1" type="text" class="form-control @error('email') is-invalid @enderror" name="contact_phone_number_1" value="{{ old('contact_phone_number_1') }}" required autocomplete="contact_phone_number_1">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_name_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Name') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="contact_name_2" type="text" class="form-control @error('email') is-invalid @enderror" name="contact_name_2" value="{{ old('contact_name_2') }}" required autocomplete="contact_name_2">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_phone_number_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Phone') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="contact_phone_number_2" type="text" class="form-control @error('email') is-invalid @enderror" name="contact_phone_number_2" value="{{ old('contact_phone_number_2') }}" required autocomplete="contact_phone_number_2">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('Event Type') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="type" type="text" class="form-control @error('email') is-invalid @enderror" name="type" value="{{ old('type') }}" required autocomplete="type">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="location" class="col-md-4 col-form-label text-md-right">{{ __('Event Location') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="location" type="text" class="form-control @error('email') is-invalid @enderror" name="location" value="{{ old('location') }}" required autocomplete="location">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">

                                    @foreach ($extras as $extra)
                                        
                                    <label for="extra" class="col-md-4 col-form-label text-md-right"></label>
        
                                    <div class="col-md-6">
                                        <input type="checkbox" id="checkbox{{$extra->id}}" name="checkbox{{$extra->id}}" >
                                        <label for="checkbox{{$extra->id}}">{{$extra->name}}</label><br>
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                    @endforeach
                                </div>

                                <div class="form-group row">
                                    <label for="number_of_guests" class="col-md-4 col-form-label text-md-right">{{ __('Number Of Guests') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="number_of_guests" type="text" class="form-control @error('email') is-invalid @enderror" name="number_of_guests" value="{{ old('number_of_guests') }}" required autocomplete="number_of_guests">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="notes" class="col-md-4 col-form-label text-md-right">{{ __('Notes') }}</label>
        
                                    <div class="col-md-6">
                                        <input id="notes" type="text" class="form-control @error('email') is-invalid @enderror" name="notes" value="{{ old('notes') }}" required autocomplete="notes">
        
                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Next') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
                   
                    <div><a href =  "{{route('events.create')}}"> Submit Request</a></div>
                    <h1>List of Events</h1>
                    <table class = "table">
                        <tr>
                            <th>id</th><th>Date</th><th>Type</th><th>Location</th><th>Name</th><th>Phone</th><th>Status</th><th>Updated</th><th>Edit</th><th>Delete</th><th>View</th>
                        </tr>
                        <!-- the table data -->
                        @foreach($events as $event)
                            <tr>
                                <td>{{$event->id}}</td>
                                <td>{{$event->date}}</td>
                                <td>{{$event->type}}</td>
                                <td>{{$event->location}}</td>
                                <td>{{$event->contact_name_1}}</td>
                                <td>{{$event->contact_phone_number_1}}</td>
                                <td>{{$event->status->name}}</td>
                                <td>{{$event->created_at}}</td>

                                <td>
                                    <a href = "{{route('events.edit',$event->id)}}">Edit</a>
                                </td>
                                <td>
                                    <a href = "{{route('events.delete',$event->id)}}">Delete</a>
                                </td>
                                <td>
                                    <a href = "{{route('events.view',$event->id)}}">View</a>
                                </td>
                            </tr>
                        @endforeach
                    </table>

@endsection

resources/views/events/view.blade.php
@extends('layouts.app')

@section('content')
                   
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">{{ __('Submit request') }}</div>
        
                        <div class="card-body">
                            <form method="post" action="{{ route('events.view', $event->id) }}">
                                @csrf
        
                                <div class="form-group row">
                                    <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Event Date') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->date}}
                                    </div>
                                </div>
        
                                <div class="form-group row">
                                    <label for="contact_name_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Name') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->contact_name_1}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->contact_email}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_phone_number_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Phone') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->contact_phone_number_1}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_name_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Name') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->contact_name_2}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="contact_phone_number_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Phone') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->contact_phone_number_2}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('Event Type') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->type}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="location" class="col-md-4 col-form-label text-md-right">{{ __('Event Location') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->location}}
                                    </div>
                                </div>
                                @foreach($extras as $extra)
                                <div class="form-group row">
                                    <label for="checkbox{{$extra->id}}" class="col-md-4 col-form-label text-md-right"></label><br>
                                    <div class="col-md-6">
                                        {{$extra->name}}
                                    </div>

    
                                </div>
                                @endforeach
                                <div class="form-group row">
                                    <label for="number_of_guests" class="col-md-4 col-form-label text-md-right">{{ __('Number Of Guests') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->number_of_guests}}
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="notes" class="col-md-4 col-form-label text-md-right">{{ __('Notes') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->notes}}
                                    </div>
                                </div>

                                @if(isset($event->bid))
                                <div class="form-group row">
                                    <label for="bid" class="col-md-4 col-form-label text-md-right">{{ __('Bid') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->bid}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="bid" class="col-md-4 col-form-label text-md-right">{{ __('Bid Details') }}</label>
        
                                    <div class="col-md-6">
                                        {{$event->bid_summary}}
                                    </div>
                                </div>
                                @else

                                <div>
                                    <a href = "{{route('bid.create',$event->id)}}">Submit bid</a>
                                </div>
                                @endif
                                <div class="form-group row mb-0">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('OK') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection