routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('events','EventsController')->middleware('auth');
Route::get('events/delete/{id}', 'EventsController@destroy')->name('events.delete');
Route::get('events/changestatus/{cid}/{sid}', 'EventsController@changeStatus')->name('events.changestatus')->middleware('auth');
Route::get('events.view/{id}', 'EventsController@details')->name('events.view');
Route::get('bid.create/{id}', 'EventsController@createbid')->name('bid.create');
Route::get('events.index/{id}', 'EventsController@createbid')->name('bid.create');
Route::get('myevents', 'EventsController@myEvents')->name('myevents');
Route::get('mybids', 'EventsController@myBids')->name('mybids');
Route::get('bidapprove/{id}', 'EventsController@bidapproved')->name('bidapprove');

Route::get('bid.details/{id}', 'EventsController@biddetails')->name('bids.details');

Route::get('users/delete/{id}', 'UsersController@destroy')->name('users.delete');
Route::get('users.index', 'UsersController@index')->name('users.index');
Route::get('users.edit/{id}', 'UsersController@edit')->name('users.edit');
Route::post('users.update/{id}', 'UsersController@update')->name('users.update');
Route::get('users.create', 'UsersController@create')->name('users.create');
Route::post('users.store', 'UsersController@store')->name('users.store');
Route::get('users.customers', 'UsersController@customers')->name('users.customers');
Route::get('users.photographer', 'UsersController@photographer')->name('users.photographer');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/bids/create.blade.php
@extends('layouts.app')

@section('content')
                   
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Submit bid') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('events.update', $event->id) }}">
                        @method('PATCH')
                        @csrf

                        <div class="form-group row">
                            <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Event Date') }}</label>

                            <div class="col-md-6">
                                {{$event->date}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="contact_name_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Name') }}</label>

                            <div class="col-md-6">
                                {{$event->contact_name_1}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="contact_email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                {{$event->contact_email}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="contact_phone_number_1" class="col-md-4 col-form-label text-md-right">{{ __('Primary Contact Phone') }}</label>

                            <div class="col-md-6">
                                {{$event->contact_phone_number_1}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="contact_name_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Name') }}</label>

                            <div class="col-md-6">
                                {{$event->contact_name_2}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="contact_phone_number_2" class="col-md-4 col-form-label text-md-right">{{ __('Secondery Contact Phone') }}</label>

                            <div class="col-md-6">
                                {{$event->contact_phone_number_2}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">{{ __('Event Type') }}</label>

                            <div class="col-md-6">
                                {{$event->type}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="location" class="col-md-4 col-form-label text-md-right">{{ __('Event Location') }}</label>

                            <div class="col-md-6">
                                {{$event->location}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="number_of_guests" class="col-md-4 col-form-label text-md-right">{{ __('Number Of Guests') }}</label>

                            <div class="col-md-6">
                                {{$event->number_of_guests}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="status_id" class="col-md-4 col-form-label text-md-right">Status</label>
                            <div class="col-md-6">
                                <select class="form-control" name="status_id">                                                                         
                                   @foreach ($statuses as $status)
                                   @if($status->id == 2)
                                     <option value="{{ $status->id }}" selected="selected"> 
                                         {{ $status->name }} 
                                     </option>
                                   @else
                                   <option value="{{ $status->id }}"> 
                                        {{ $status->name }} 
                                    </option>
                                   @endif                                      
                                   @endforeach    
                                 </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="notes" class="col-md-4 col-form-label text-md-right">{{ __('Notes') }}</label>

                            <div class="col-md-6">
                                {{$event->notes}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="bid" class="col-md-4 col-form-label text-md-right">{{ __('Bid') }}</label>

                            <div class="col-md-6">
                                <input id="bid" type="integer" class="form-control @error('email') is-invalid @enderror" name="bid" value="{{ old('bid') }}" required autocomplete="bid">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="bid_summary" class="col-md-4 col-form-label text-md-right">{{ __('Details') }}</label>

                            <div class="col-md-6">
                                <input id="bid_summary" type="longtext" class="form-control @error('email') is-invalid @enderror" name="bid_summary" value="{{ old('bid_summary') }}" required autocomplete="bid_summary">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('OK') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/bids/details.blade.php
@extends('layouts.app')

@section('content')
                   

                    <div class="card">
                        <div class="card-header"></div>
        
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Bid Amount') }}</label>
    
                                <div class="col-md-6">
                                    {{$event->bid}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="date" class="col-md-4 col-form-label text-md-right">{{ __('Bid Details') }}</label>
    
                                <div class="col-md-6">
                                    {{$event->bid_summary}}
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">
                                {{ __('I Am Interested In') }}
                            </button>
                            <button type="submit" class="btn btn-primary">
                                <a herf = "{{route('bidapprove',$event->id)}}"> {{ __('Not Interested') }}</a>
                            </button>


                            <div class="form-group row">
                                <label for="date" class="col-md-4 col-form-label text-md-right"></label>
    
                                <div class="col-md-6">
                                    <a href = "{{route('events.view',$event->id)}}">View Event Details</a>
                                </div>
                            </div>
                               
                        </div>
                    </div>
                </div>
                @endsection

resources/views/bids/index.blade.php
@extends('layouts.app')

@section('content')
<h1>List of Bids</h1>
<table class = "table">
    <tr>
        <th>Event id</th><th>Event Date</th><th>Event Type</th><th>Event Location</th><th>Status</th><th>Bid</th><th>Bid Details</th>
    </tr>
    <!-- the table data -->
    @foreach($events as $event)
        <tr>
            <td>{{$event->id}}</td>
            <td>{{$event->date}}</td>
            <td>{{$event->type}}</td>
            <td>{{$event->location}}</td>
            <td>
                {{$event->status->name}}
            </td>
            <td>
                {{$event->bid}}
            </td>
            <td>
                <a href = "{{route('bids.details',$event->id)}}">Details</a>
            </td>

            <td>
                <a href = "{{route('events.view',$event->id)}}">View</a>
            </td>
        </tr>
    @endforeach
</table>

@endsection